# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: k8s-cloud-kms-plugin

spec:
  hostNetwork: true
  restartPolicy: Never

  volumes:
  - name: kmssocket
    hostPath:
      path: /var/run/kmsplugin
      type: DirectoryOrCreate

  containers:
  - name: kms-plugin
    image: gcr.io/cloud-kms-lab/k8s-cloud-kms-plugin:v0.1.1
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "exec /k8s-cloud-kms-plugin --project-id=alextc-k8s-lab --location-id=global --key-ring-id=ring-01 --key-id=my-key --path-to-unix-socket=/var/run/kmsplugin/grpc.sock --alsologtostderr 2>&1"]
    volumeMounts:
    - name: kmssocket
      mountPath: /var/run/kmsplugin
      readOnly: false